services:
  ors-app:
    image: openrouteservice/openrouteservice:latest
    container_name: ors-app
    ports:
      - "8080:8082"
      - "9001:9001"
    volumes:
      - ./ors-docker/graphs:/home/ors/graphs
      - ./ors-docker/files:/home/ors/files
      - ./ors-docker/config/ors-config.yml:/home/ors/config/ors-config.yml
    environment:
      REBUILD_GRAPHS: True
      CONTAINER_LOG_LEVEL: INFO
      ORS_CONFIG_FILE: /home/ors/config/ors-config.yml
      XMS: 1g
      XMX: 2g
